export const DISCOVERY_DOCUMENT_LINK = 'https://accounts.google.com/.well-known/openid-configuration';
export const CLIENT_ID = '1088545040897-mk0fes397oncumuanqb60q4joc1vetsp.apps.googleusercontent.com';
export const CLIENT_SECRET = 'UVdObnsCExfrjlG-t1CkkHmG';

export const LOGIN_PATH =
  process.env.NODE_ENV === 'development' ? 'http://localhost:3000/login' : 'https://da-form.web.app/login';

export const TOKEN_INFO_PATH = 'https://oauth2.googleapis.com/tokeninfo?id_token=';
export const API_KEY =
  'u09wjaopfp98a4uwjp9839tq9pg84whtbNOUIFHWE(*$HOfn98h4q9nw89ybntn927ynw5b98t7yw498t9w845tbny457tw087wy5';

export const SCRIPT_PROD_URL =
  'https://script.google.com/macros/s/AKfycbxYuh0etGTebCE2BH2fRsDo6X6Jy4PHUFlNwvXSyxqULDjBS8FloD_ghSI2x7KEXrVlaA/exec';

export const BRAND_NAME = 'DA Form';

export const daItemOptions = [
  'TURBO DRYER',
  'STRAIGHT UP CERAMIC',
  'CERASILK STYLING IRON',
  'MINI TRAVEL DRYER',
  'CERASILK CURLING IRON',
  'PRIME TRNSFORMING SPRAY',
  'SHINE REFINING MIST',
  'PRIME SHINE STYLNG SYST',
  'ALL TIED UP KNOTTED HR',
  'PIN IT UP HAIR PINS',
  'WORD PLAY HAIR PINS',
  'ESSENTIALS ACCESSORIES',
  'LETS ESCPE DRAWSTRNG B',
  'IMAGINE DRAWSTRNG BAG',
  'BLOWN AWAY DRAWSTRING',
  'GLOSSIE CRMIC STYLNG B',
  'BLU+MINI DRYER GWP',
  'BEAT THE HEAT DRAWSTR',
  'GET YOUR GLOSS DRAWST',
  'AIRLESS BLOWOUT',
  'MINI DRYER (ULTA)',
  'CURATION CERA STYLING',
  'MAXPRIME BLWOUT REVOL',
  'MXPRIMEW2D BLOWOUT',
  'PRIME BLOWOUT REVOLVI',
  'FREESTYLE IONIC CERMC',
  'MAVEN CERAMIC HOT AIR',
  'STRAIGHT UP MINI',
  'TURBO MAX IONIC HAIR',
  '7X SMART DRYER',
  'FREESTYLE MAX',
  'DIFFUSER FOR 7X DRYER',
  'DIFFUSER FOR TURBO DRYER',
  'AIRLESS-WHITE STE BOX',
  '1-WAY RI 1-1/4 PURPLE',
  '1-WAY RI 1-1/4 PINK',
  '1-WAY RI 1-1/4 RED',
  '1-WAY RI 1.25 PURP-RH',
  '1-WAY RI 1.25 PINK-RH',
  '1-WAY RI 1.25 RED-RH',
  '2 MAX RI 3/4 WHITE-RH',
  '2 MAX RI 3/4 WHITE',
  'STRAIGHT UP MAX',
  'MAX BLK 32-MATTE#18',
  'MAX BLK 19-MATTE#18',
  'WANDERLUST FLAT IRON',
  'SECTIONING COMB',
  'DETANGLING COMB',
  'SATIN SCRUNCHIE SET 1',
  'SCARF SCRUNCHIE SET 1',
  'HAIR BARRETTES SET 1',
  'THERMAL ROUND BRUSH',
  'THERMAL TWISTER BRUSH',
  'VENTED PADDLE BRUSH',
  'SMOOTHNG PADDLE BRUSH',
  'HEAT RES TRAVEL BAG',
  'MAX PRIME WET TO DRY',
  'MAX PRIME WET TO DRY',
  'Solutions PROTECT',
  'Solutions HOLD',
  'Solutions GLOSS'
];
